### ISSUE TITLE
Can tepitope be usd to predict MHC-II binders?

### ISSUE THREAD

**Issue by richelbilderbeek** [BenPorebski/tepitope#3]
Hi @BenPorebski,

I am looking for free and open source (FOS) MHC-II epitope predictor, such as EpiJen, NetMHCII, NetMHCIIpan, TEPITOPE, TEPITOPEpan, PROPRED, RANKPEP, SVRMHC.Because of the short README, it is unclear if tepitope indeed can do this.

Is tepitope indeed a FOSS MHC-II epitope predictor? If yes, which software license does it have?

**Comment by BenPorebski** [comment]
Hi @richelbilderbeek,

This github is a simple python implementation of TEPITOPE, which uses their scoring matrices to predict MHC-II epitopes.
Unless there's a bug in the code, it should give the same prediction output as the TEPITOPE webserver.

There is currently no licence on this repo, but I'm happy for anyone to do whatever they want with it. I don't know if the scoring matrices fall under any license, but I shall look into this and update the repo.

**Comment by BenPorebski** [comment]
I have added a licence to the repository as unlicence. It is free for anyone to do whatever they want with the source code. Scoring matrices were built from the tepitope paper (https://www.nature.com/articles/nbt0699_555) and may have some copyright associated with it.

As an MHC-II epitope predictor, this is almost certainly not state of the art anymore.
